name: 'Containerized'

inputs:
  USERNAME:
    description: 'Your Quizlet username'
    type: string
    required: true
  PASSWORD:
    description: 'Your Quizlet password'
    type: string
    required: true
  FILEPATH:
    description: 'The path to the file to upload'
    type: string
    required: true
  SETID:
    description: 'Study setid'
    type: string
    required: true
  HEADLESS:
    description: 'launch headless browser'
    type: boolean
    required: true

runs:
  using: 'docker'
  image: '../../../Dockerfile'
  env:
    USERNAME: ${{ inputs.USERNAME }}
    PASSWORD: ${{ inputs.PASSWORD }}
    FILEPATH: ${{ inputs.FILEPATH }}
    SETID: ${{ inputs.SETID }}
    HEADLESS: ${{ inputs.HEADLESS }}
    LOG: '/home/runner/work/quizlet_action/quizlet_action/'
    