name: quizlet_push
on:
  push:
    paths:
      - 'formatted/*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
        - run: npm install
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: start script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FILEPATH: 'formatted/vocalbulary'
        run: |
          echo "$FILEPATH"
          node request.js
