name: quizlet_vocabulary_push
on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - 'formatted/*'
      - 'backup/vocabulary/*'

jobs:
  vocalbulary_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/containerized
        with:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FILEPATH: 'formatted/vocabulary'
          SETID: '683855692'
          HEADLESS: true
